#!/bin/bash
# shellcheck disable=1091
. script/functions.in # debug mode, will be changed later

if [ $EUID != 0 ]; then
	msg_error "You must run this program as root!"
	exit 1
fi

case "$1" in
	"list")
		case "$2" in
			"rc") list_rc_services ;;
			"runit") list_runit_services ;;
			"") list_rc_services; list_runit_services ;;
			*) msg_error "$1: unknown parameters" ;;
		esac
	;;

	# up+down + LSB-compatible init-script actions
	"up"|"down"|"start"|"stop"|"reload"|"restart"|"shutdown"|"force-stop"|"force-reload"|"force-restart"|"force-shutdown"|"try-restart")
		if runit_sv_enabled "$2"; then
			sv "$1" "$2"
			## RC GOES HERE
		else
			msg_error "$2: runit service is not enabled!"
		fi
	;;

	"status")
		if runit_sv_enabled "$2"; then
			sv "$1" "$2"
		elif rc_sv_enabled "$2"; then
			msg_ok "$2: rc service enabled"
		elif runit_sv_available "$2"; then
			msg_error "$2: runit service is not enabled"
		elif rc_sv_available "$2"; then
			msg_error "$2: rc service is not enabled"
		else
			msg_error "$2 is not an existing runit or rc service!"
		fi
	;;

	"pause"|"cont"|"hup"|"alarm"|"intmsg_errorupt"|"quit"|"1"|"2"|"term"|"kill")
		if runit_sv_enabled "$2"; then
			sv "$1" "$2"
		elif runit_sv_available "$2"; then
			msg_error "$2: runit service is not enabled"
		else
			msg_error "$2 is not an existing runit service or rc service is not supported!"
		fi
	;;
	"")
		msg_error "usage: service command ..."
		exit 1
	;;
	*)
		msg_error "$1: unrecognized command"
		msg_error "$1: "
		exit 1
esac
